In [1]:
import numpy as np 

a= np.array([1,2,3,4])

print(a);

[1 2 3 4]


In [6]:
import time

a= np.random.rand(100000)
b = np.random.rand(100000)

tic = time.time()
c= np.dot(a,b)
toc= time.time()

print("Vectorized version "+str(1000*(toc-tic))+"ms")

c= 0
tic = time.time()
for i in range(100000):
    c+=a[i]*b[i]
    
toc = time.time()

print(c)
print("For loop "+ str(1000*(toc-tic))+"ms")

Vectorized version 0.0ms
25086.423299345286
For loop 43.03383827209473ms


In [9]:

A= np.array([[56,0,4.4,68],
           [1.2,104,52,8],
           [1.8,135,99,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [10]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [11]:
percentage=100* A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [13]:
k= np.random.randn(5,1)
print(k)

[[ 0.31178817]
 [-0.69882198]
 [-0.53086747]
 [ 2.01706427]
 [ 1.0665986 ]]


In [14]:
print(k.T)

[[ 0.31178817 -0.69882198 -0.53086747  2.01706427  1.0665986 ]]


In [17]:
print (np.dot(k,k.T))

[[ 0.09721187 -0.21788443 -0.1655182   0.62889679  0.33255283]
 [-0.21788443  0.48835215  0.37098185 -1.40956884 -0.74536254]
 [-0.1655182   0.37098185  0.28182027 -1.0707938  -0.56622249]
 [ 0.62889679 -1.40956884 -1.0707938   4.06854826  2.15139792]
 [ 0.33255283 -0.74536254 -0.56622249  2.15139792  1.13763257]]
